LABELS = {
    "athena": "Amazon Athena",
    "bigquery": "BigQuery",
    "clickhouse": "ClickHouse",
    "duckdb": "DuckDB",
    "mssql": "Microsoft SQL Server",
    "mysql": "MySQL",
    "parquet": "Parquet",
    "postgres": "PostgreSQL",
    "snowflake": "Snowflake",
    "sqlite": "SQLite",
    "BigQueryDefaultAuth": "Default auth",
    "BigQueryServiceAccountJsonAuth": "Service account JSON credentials",
    "BigQueryServiceAccountKeyFileAuth": "Service account key file",
    "SnowflakeKeyPairAuth": "Key pair",
    "SnowflakePasswordAuth": "Password",
    "SnowflakeSSOAuth": "SSO",
    "connection.auth.type": "Authentication type",
    "connection.host": "Host",
    "connection.port": "Port",
    "connection.database": "Database",
    "connection.schema": "Schema",
    "connection.username": "Username",
    "connection.password": "Password",
    "connection.account": "Account",
    "connection.warehouse": "Warehouse",
    "connection.role": "Role",
    "connection.path": "File path",
    "connection.project": "Project",
    "connection.dataset": "Dataset",
    "connection.location": "Location",
    "connection.auth.credentials_file": "Credentials file",
    "connection.auth.key_file": "Key file",
    "connection.auth.token": "Token",
}