name: Setup uv and project
inputs:
  uv-version:
    description: "uv version"
    required: false
    default: "0.10.5"
  python-version:
    description: "python version to install"
    required: false
    default: "3.12"
  extra-dependencies:
    description: "extra dependencies to install"
    required: false
  prune-cache:
    description: "prune cache after installation"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
        prune-cache: ${{ inputs.prune-cache }}

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24.5.0"

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.14.0

    - name: Install dependencies
      shell: bash
      run: uv sync --python ${{ inputs.python-version }} ${{ inputs.extra-dependencies }}
