name: E2e tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-tests-ubuntu:
    name: "Run e2e tests on ubuntu"
    runs-on: sre-eqx-kata
    permissions:
      contents: write
      pull-requests: write
      checks: write
    env:
      UV_LINK_MODE: copy
    steps:
      - uses: actions/checkout@v5

      - name: Set up project
        uses: ./.github/actions/setup-project
        with:
          python-version: 3.12
          extra-dependencies: "--group e2e-tests"

      - name: Download Allure
        if: always()
        continue-on-error: true
        run: |
          npm install allure

      - name: Run e2e tests
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
          SNOWFLAKE_TEST_USER_PROGRAM_TOKEN: ${{ secrets.SNOWFLAKE_TEST_USER_PROGRAM_TOKEN }}
        run: uv run pytest e2e-tests

      - name: Generate Allure report
        if: always()
        continue-on-error: true
        run: |
          npx allure generate

      - name: Run Allure Action
        uses: allure-framework/allure-action@v0
        if: always()
        continue-on-error: true
        with:
          report-directory: "./allure-report"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Tests artifacts
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          compression-level: 6
          name: artifacts
          path: e2e-tests/artifacts/

      - name: Upload allure artifacts
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          compression-level: 6
          name: artifacts
          path: allure-report