name: E2e tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-tests-ubuntu:
    name: "Run e2e tests on ubuntu"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    env:
      UV_LINK_MODE: copy
    steps:
      - uses: actions/checkout@v5

      - name: Set up project
        uses: ./.github/actions/setup-project
        with:
          extra-dependencies: "--group e2e-tests"
          prune-cache: false

      - name: Run e2e tests
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_TEST_USER: ${{ secrets.SNOWFLAKE_TEST_USER }}
          SNOWFLAKE_PRIVATE_TOKEN: ${{ secrets.SNOWFLAKE_PRIVATE_TOKEN }}

          BQ_PROJECT: ${{ secrets.BQ_PROJECT }}
          BQ_DATASET: ${{ secrets.BQ_DATASET }}
          BQ_SERVICE_ACCOUNT_JSON: ${{ secrets.BQ_SERVICE_ACCOUNT_JSON }}
        run: uv run pytest e2e-tests --alluredir=allure-results-ubuntu

      - name: Upload Tests artifacts
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          retention-days: 10
          compression-level: 6
          name: artifacts
          path: ./e2e-tests/artifacts/

      - name: Upload Allure artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          retention-days: 10
          compression-level: 6
          name: allure-results-ubuntu
          path: ./allure-results-ubuntu

  allure-report:
    needs: [ e2e-tests-ubuntu ]
    name: Generate allure report
    runs-on: ubuntu-latest
    continue-on-error: true
    if: always()
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v6

      - name: Download allure results
        uses: actions/download-artifact@v6
        with:
          name: allure-results-ubuntu
          path: allure-results-ubuntu

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: allure-results-ubuntu
          allure_history: allure-history

      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
