name: publish-pypi

on:
  push:
    tags:
      # Publish on stable version tags only, e.g., v0.1.0
      - 'v[0-9]*.[0-9]*.[0-9]*'
      - '!v*.dev*'

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    environment:
      name: pypi

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.5"
          enable-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.5.0"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Build
        run: uv build

      # Check that basic features work and we didn't miss to include crucial files
      - name: Smoke test (wheel)
        run: uvx --from dist/*.whl databao --help
      - name: Smoke test (source distribution)
        run: uvx --from dist/*.tar.gz databao --help

      - name: Publish
        run: uv publish
